#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Yasushi Ando yasushigit@gmail.com
# SPDX-License-Identifier: GPL-3.0-only
import sys

def main():
    text = sys.stdin.read()
    if text == "":
        num_lines = 0
    else:
        num_lines = text.count("\n")
        if not text.endswith("\n"):
            num_lines += 1

    num_words = len(text.split())

    num_chars = len(text)

    print(f"lines:{num_lines} words:{num_words} chars:{num_chars}")

if __name__ == "__main__":
    main()