#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Yasushi Ando yasushigit@gmail.com
# SPDX-License-Identifier: GPL-3.0-only
import sys

def main():
    text = sys.stdin.read()

    lines = len(text.splitlines())

    words = len(text.split())

    chars = len(text)

    print(f"lines:{lines} words:{words} chars:{chars}")

if __name__ == "__main__":
    main()